dataset:
  base_dir: "YOLO_Ensembles_for_Real-Time_Small_Object_Detection_on_Moving_Drones_with_Reference_Image\data\train"
  output_dir: "yolo_dataset"

split:
  train_ratio: 0.7

classes:
  id: 0
  name: "target_object"