model:
  yolov8n: 'YOLO_Weights/YOLOv8-n.pt'
  yolov11n: 'YOLO_Weights/YOLOv11-n.pt'
  
  imgsz1: 640
  imgsz2: 1024

data:
  test_dir: 'data/public_test/samples'
  ref_img_dir: 'Reference Images (Uncleaned)'

output:
  file: 'predictions.json'

inference:
  confidence_threshold: 0.25